# Generated by Django 4.2.8 on 2024-01-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('book_name', models.CharField(max_length=200)),
            ],
        ),
    ]
